### ISSUE TITLE
Armor Issues

### ISSUE THREAD

**Issue by Hexopus** [NTrixner/RaggedLandsPenAndPaper#133]
As of v20 

- [x] **Linen Robes** are missing a descriptor
- [x] **Linen** is worse (no warming on Cloth, same stats on Light) & more expensive than **Fleece**
- [x] **Boiled Leather Jacket** is worse (no insulation) & significantly more expensive than **Leather Jacket**
- [x] **Steel** is exactly the same as **Iron** & significantly more expensive
- [x] 500gp for **Heavy Armor Training** seems very prohibitive in combination with the already high cost of Heavy Armor (maybe on purpose, lol).
- [x] Armor's **Agility cap** might require rephrasing to state order of operations (I assume it is checked last, and does not actively reduce)

**Comment by NTrixner** [comment]
A lot of these are probably the result of removing wound thresholds... I'll work through them, but I don't think it will be necessary for sunday's playtest - I'll move this into long term.

Regarding the Agility cap - what exactly do you mean with "does not actively reduce" ? Basically it's applied last, so unless I'll introduce a magic item like "This increases your Agility by 2, even after reduction from Armor", this is a hard cap.

**Comment by NTrixner** [comment]
I see what you mean - will change it

**Comment by NTrixner** [comment]
Regarding the heavy armor price - yes, that is restrictive on purpose. A character should move from at most medium to heavy armor during gameplay.

**Comment by Hexopus** [comment]
How do you repair wood armor btw?

**Comment by NTrixner** [comment]
That will be part of the crafting system

**Comment by Hexopus** [comment]
I am intrigued.

Next question: If an Ignan wearing Wood Armor takes 2 heat damage, which his racial ability reduces to 0, does the armor burn? RAW it currently doesn't :D

**Comment by Hexopus** [comment]
Idk. Ignan with Wood Armor seems like a potent tank choice for Sunday. But I'd love to see it play out, tbh, so let's leave it for now.

Last question: My muddy brain remembers that damage types are reduced seperately, which would make the performance of Maces and Morning Stars abysmal against (Heavy) Armor and only average against non-armored. Is this intended?

**Comment by NTrixner** [comment]
The idea there was to provide diversity of damage types without having to switch the weapon. I think what's not as obvious/needs to be more directly stated, is that bonuses to weapon damage apply to each damage type of a weapon. i.e. daevana, brutal attack, etc. all go to both damage types.

**Comment by Hexopus** [comment]
Uh... not sure if you want that. A brutal strike with a daevan Morning Star would deal 4d6 +6 (10-30)damage then o_o (AP, 5 stamina). But I will add some Weapon Issues at night, maybe we can discuss it there.

**Comment by NTrixner** [comment]
Changed it to you can choose which damage type gets which bonus.
