### ISSUE TITLE
Weapon Issues

### ISSUE THREAD

**Issue by Hexopus** [NTrixner/RaggedLandsPenAndPaper#134]
o **Simple Weapon Training:** Grants proficiency with ALL simple weapons, but following trainings only grant it to ONE single type? (This is but a question)
o **Weapon Training:** Should probably be called "Regular Weapon Training" and refer to this new group, instead of listing what it doesn't refer to. 
o **Siege Weapon Training & Shield Training:** Missing in action.

o **Weapon Quality:** So, a Mastercraft Short Spear (1d6+3) costs 15 gold, and a broken Arming Sword (1d6-3) costs 88 gold? I reckon we don't want players to buy this at the start, right? Or... ever? Super-duper-shiny Lances would probably never sell for as little as 120gp, the same as a regular Battle Axe.

o **Unarmed Combat:** This is either too quick or too strong, cause it beats a Light Hammer with Double DPS (or DPAP, to be exact). Actually it beats ~2/3rds of all weapons at raw DPAP. Similar stuff with Throwing Stones, if I read them correctly.
o **Dagger:** Only scales with AG? 
o **Short Sword:** Nearly strictly better than the Rapier (other than not parrying piercing) , but way cheaper and gets a (probably) pointless ability of spending more AP for lower damage on a (most likely) worse damage type. I am confusion.

o **Battle Axe:** Probably should be a 3AP attack, instead of 4AP, to fit between Hand Axe and Bearded Axe more neatly. 
o **Mace/Morning Star:** Talked about this already. Essentially doubling any bonus/malus on the damage is very risky in a damage reduction system. These two could easily flip-flop between being useless and OP. Just a warning here, I guess.
o **Great Axe:** No matter how I calculate it, 4d8 seems a bit excessive. 
o **Great Sword:** Same issue as with Short Sword, this _downgrades_ to cutting damage, which appears to be worse (blockable, and equal/worse against all armor). I feel that Arming Swords do it right, by granting options. 

o **Bow:** Not sure whether 10 passus is corrrect, while Slings have 30 passus range? 
o **Flintlock Rifle:** Compared to the pistol variant, 4AP to shoot seems inappropriate. 
o **Ballista:** "Can" or "Has" to be operated? Also, I fail to see the point of Siege weapons, at the moment. I know it's a system document, not a PHB, but it feels strongly like later-work.

o **Shields:** Some have an AP cost for blocking, others don't. Some block "weapon damage", others list the 3 physical damage types. I am 80% sure those are typos. 
o **Round Shield:** Refers to a non-existent "Parry". 

o **Common Hammer:** RIP, you were most beloved in v20.

**Comment by NTrixner** [comment]
In order to keep issues separated, I'll now treat the parts of #138 that belong to weapons as part of this issue.

**Comment by NTrixner** [comment]
Fixed at least a bit, we'll have to re-examine the weapons now and have another look - would be very thankful for that!
