### ISSUE TITLE
Change Looting

### ISSUE THREAD

**Issue by johannes-z** [NTrixner/RaggedLandsPenAndPaper#29]
Loot just disappears after enemies are killed. Picking up their weapons is fundamental. Rolling should just be done for converting to crafting materials or finding hidden stashes.

Edit by @NTrixner: Will do both - where it makes sense to have someone find stuff we will do that, and where it makes sense to receive things from the enemy we will instead do that. Some enemies will have both.

Looting tables in this version:
- [ ] dog guarding
- [ ] dog hunting
- [ ] dog war
- [ ] wolf
- [ ] wolf alpha
- [ ] dire wolf
- [ ] dire wolf alpha
- [ ] raptor wild
- [ ] spitfly
- [ ] fire beetle
- [ ] giant spider
- [ ] giant snake
- [x] clockwork automaton
- [ ] clockwork warrior
- [ ] clockwork guard
- [x] clockwork augur
- [ ] goblin
- [ ] goblin warrior
- [ ] goblin shaman
- [ ] goblin scout
- [ ] orc
- [ ] ogre
- [ ] bandit 
- [ ] bandit scout
- [ ] bandit mage
- [ ] guard
- [ ] soldier

**Comment by NTrixner** [comment]
Looting tables in this version:
- [] dog guarding
- [] dog hunting
- [] dog war
- [] wolf
- [] wolf alpha
- [] dire wolf
- [] dire wolf alpha
- [] raptor wild
- [] spitfly
- [] fire beetle
- [] giant spider
- [] giant snake
- [] clockwork automaton
- [] clockwork warrior
- [] clockwork guard
- [] clockwork augur
- [] goblin
- [] goblin warrior
- [] goblin shaman
- [] goblin scout
- [] orc
- [] ogre
- [] bandit 
- [] bandit scout
- [] bandit mage
- [] guard
- [] soldier

**Comment by NTrixner** [comment]
now part of #15
