### ISSUE TITLE
My suggestions for improvement

### ISSUE THREAD

**Issue by johannes-z** [NTrixner/RaggedLandsPenAndPaper#31]
- [x] 1. Fit more information onto one page. E.g. different column-layout, less margin, etc.
- [x] 2. Add informations and examples. E.g. describe character archetypes in attributes section (a thief requires more agility and dex than intelligence for example).
- [x] 3. Make skills stand out more. Skills don't matter right now in the beginning of the game. Adventurers, even at the start of their quest should be more iconic.
- [x] 4. #30 Let divine rest affect multiple (party) members.
- [x] 5. #29 Loot just disappears after enemies are killed. Picking up their weapons is fundamental. Rolling should just be done for converting to crafting materials or finding hidden stashes.
- [x] 6. Fumbles and crits for skills on a `d12` seem *wrong*.  A `8%` chance to fail or succeed on **any** task disregarding the character's stats is too much. 

*more may come

**Comment by NTrixner** [comment]
1. will do
2. will do in steps
3. should be achieved by the new system
4. will do
5. will do
6. already working like that, we tried a different version for the playtest johannes was in.
